name = "supaflare-worker"
main = 'index.js'
usage_model = 'bundled'
route = ''
account_id = ''
zone_id = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2021-10-10"
kv_namespaces = [ 
  { binding = "SUPAFLARE", id = "a254b911651b42af9d306e69c558ebd5", preview_id = "78c8caceaf6b4228aea01f725ef70527" }
]
