name: Cloudflare Pages Deployment

on:
  workflow_dispatch:
  schedule:
  - cron: "0 2 1 * *"
      
  push:
    branches:
      - master
    paths:
      - app/**
      - .github/workflows/deploy-worker.yml

defaults:
  run:
    working-directory: app

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Page
    steps:
      - name: Invoke Deploy Master Hook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.CF_PAGES_MASTER_WEBHOOK_URL }}
          webhook_secret: "no_secret_required"
